issuer: http://127.0.0.1:5556/dex

storage:
  type: sqlite3
  config:
    file: examples/dex.db

# Configuration for the HTTP endpoints.
web:
  http: 0.0.0.0:5556

grpc:
  addr: 127.0.0.1:5557
  tlsCert: server.crt
  tlsKey: server.key
  tlsClientCA: ca.crt

staticClients:
  - id: example-app
    redirectURIs:
     - 'http://127.0.0.1:3000/auth/oauth2/callback'
     - 'http://127.0.0.1:5555/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

connectors:

oauth2:
   skipApprovalScreen: true
# Let dex keep a list of passwords which can be used to login to dex.
enablePasswordDB: true

expiry:
  deviceRequests: "5m"
  signingKeys: "24h"
  idTokens: "24h"

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    groups:
       - "admin"
       - "super"
       - "create_admingroup"